const ACTION_TYPES = {
  //get
  GET_MESSAGES_REQUEST: "GET_MESSAGE_REQUEST",
  GET_MESSAGES_SUCCESS: "GET_MESSAGE_SUCCESS",
  GET_MESSAGES_ERROR: "GET_MESSAGE_ERROR",
  //create
  CREATE_MESSAGE_REQUEST: "CREATE_MESSAGE_REQUEST",
  CREATE_MESSAGE_SUCCESS: "CREATE_MESSAGE_SUCCESS",
  CREATE_MESSAGE_ERROR: "CREATE_MESSAGE_ERROR",
};

export default ACTION_TYPES;
